version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./animals-manager/.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  nest-app: 
    build: ./animals-manager
    ports:
      - 3000:3000
    volumes:
      - ./animals-manager:/app
      - /app/node_modules
    command: npm run start:dev
    env_file:
      - ./animals-manager/.env
    depends_on:
      - mongodb

  angular-ui:
    build: ./animals-manager-ui
    ports:
      - 4200:4200
    volumes:
      - ./animals-manager-ui:/ui-app
      - /ui-app/node_modules
    depends_on:
      - nest-app

volumes:
  mongodb_data_container: